openapi: 3.0.0
info:
  version: 1.0.0
  title: DataMigration
  contact:
      email: bramani@apple.com
servers:
- url: 'http://localhost:8080/'
  description: Development server
- url: https://staging.acm.apple.com/v1
  description: Staging server
- url: https://api.acm.apple.com/v1
  description: Production server
  
paths:
  /user:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /data/migrate/daterange:
    post:
        parameters:
            - name:indexname
            in:query
            description:name of the ES index
            required:true
            schema:
                type: string
            - name:domain
            in:query
            description:name of the domain
            required:true
            schema:
                type: string
            - name:sortBy
            in:query
            description:name of the field in ES index to sort by
            required:true
            schema:
                type: string
            - name:rowLimit
            in:query
            description:max no of rows to migrate
            required:true
            schema:
                type: integer
                format:int32
            - name:fromDate
            in:query
            description:start date
            required:true
            example: "2021-01-30T08:30:00Z"
            schema:
                type: string
                format:date-time
            - name:toDate
            in:query
            description:end date
            required:true
            example: "2021-01-30T08:30:00Z"
            schema:
                type: string
                format:date-time
    
components:
        
  schemas:
    ResponseOutput:
     type:object
     required:
        - body
        - statusMap
    properties:
        body:
            type:object
            additionalProperties:
                $ref: '#/components/Body'
        statusMap:
            type:object
            additionalProperties:
                $ref: '#/components/StatusMap'

    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string

    StatusMap:
        type: object
        additionalProperties:true

    Body:
        type:object

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string