openapi: 3.0.0
info:
  title: DataMigration
  contact:
    email: bramani@apple.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/athreya86/DataMigration/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080/
  description: Development server
- url: https://staging.acm.apple.com/v1
  description: Staging server
- url: https://api.acm.apple.com/v1
  description: Production server
paths:
  /data/migrate/daterange:
    post:
      tags:
      - migrate
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: migrateData
      parameters:
      - name: indexname
        in: query
        description: name of the ES index
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: domain
        in: query
        description: name of the ES domain
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: sortBy
        in: query
        description: name of the field ES index to sort by
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: plaintext
        in: query
        description: plaintext data
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: rowLimit
        in: query
        description: max no of rows
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: fromDate
        in: query
        description: start date
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date-time
      - name: toDate
        in: query
        description: end date
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date-time
      responses:
        "200":
          description: Successful response for data migration by daterange
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOutput'
        "401":
          description: Unauthorized error for data migration by daterange
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    StatusMap:
      type: object
      additionalProperties: true
    Body:
      type: object
    ResponseOutput:
      required:
      - body
      - statusMap
      type: object
      properties:
        body:
          $ref: '#/components/schemas/Body'
        statusMap:
          $ref: '#/components/schemas/StatusMap'
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
